export { PRETTIER_OPTIONS } from './core'
export { exbotanical as default } from './factory'

export type { OptionsPrettier } from './options'
export type { OptionsDocker } from './plugins/docker'
export type { OptionsIni } from './plugins/ini'
export type { OptionsNginx } from './plugins/nginx'
export type { OptionsProperties } from './plugins/properties'
export type { OptionsShell, ShellVariant } from './plugins/shell/options'
export type { OptionsSolidity } from './plugins/solidity'
export type { OptionsSql, SqlLetterCase } from './plugins/sql'
export type { OptionsToml } from './plugins/toml'
export type { OptionsXml } from './plugins/xml'
